version: "2.0"

services:

  lb:
    image: hypriot/rpi-traefik:v1.1.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pirate/rasp-workspace/conf/traefik:/etc/traefik
    labels:
      traefik.port: "8080"
      traefik.frontend.rule: "Host:traefik.pi2.coupin.tk"
      traefik.backend: "traefik"
    networks:
      - middle

  httpd:
    image: hypriot/rpi-busybox-httpd
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:pi2.coupin.tk"
      traefik.backend: "httpd"
    depends_on: 
      - lb
    networks:
      - middle

networks:
  middle: