version: "2.0"

services:

  lb:
    image: hypriot/rpi-traefik:v1.1.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pirate/rasp-workspace/conf/traefik:/etc/traefik 
      - /mnt/pi2/traefik/acme:/etc/traefik/acme
    labels:
      traefik.port: "8080"
      traefik.frontend.rule: "Host:pi2.local"
      traefik.backend: "traefik"
      portainer: "hide"
    networks:
      - middle

  httpd:
    image: hypriot/rpi-busybox-httpd
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:pi2.coupin.tk, coupin.tk"
      traefik.backend: "httpd"
    depends_on: 
      - lb
    networks:
      - middle

  portainer:
    image: portainer/portainer:linux-arm-1.11.4
    networks:
      - middle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/pi2/portainer:/data
    labels: 
      traefik.port: "9000"
      traefik.frontend.rule: "Host:portainer.pi2.coupin.tk"
      traefik.backend: portainer
      portainer: "hide"
    command: -l portainer=hide --templates https://raw.githubusercontent.com/tcoupin/rasp-workspace/master/conf/portainer/templates.json
    
networks:
  middle: